### ISSUE TITLE
Add support for LUH-D301S-WEU

### ISSUE THREAD

**Issue by manuelmayer-dev** [formatBCE/HA_VeSync_Classic300s#6] opened 2022-03-01 18:36 UTC
Basically this is a Dual 200S but with another name, selled in Europe. It is also supported by the pyvesync library.

I tried to add it myself but for some reason it did not work but I'm also not a Python developer, maybe you can bring it to work :)
I'm using Home Assistant version 2022.2.9 and pyvesync is installed with version 1.4.3

I wrote a little test script with the pyvesync library that outputs the device information:
`Device Name:... Luftbefeuchter`
`Model: ........ LUH-D301S-WEU`
`Subdevice No: . None`
`Status: ....... on`
`Online: ....... online`
`Type: ......... wifi-air`
`CID: .......... xxxxxxxxxxxxxxxxxxxxxxxxx`
`UUID: ......... xxxxxxxxxxxxxxxxxxxxxxxxxxxx`
`Mode: ....................... auto`
`Humidity: ................... 52 percent`
`Mist Virtual Level: ......... 1`
`Mist Level: ................. 1`
`Water Lacks: ................ False`
`Humidity High: .............. False`
`Water Tank Lifted: .......... False`
`Display: .................... True`
`Automatic Stop Reach Target:  False`
`Auto Target Humidity: ....... 55 percent`
`Automatic Stop: ............. True`
`None`

**Comment by formatBCE** [comment] 2022-03-01 18:42
Sorry, I postponed activity here for now - helping Ukrainian soldiers.
Will get back, when time allows.

**Comment by manuelmayer-dev** [comment] 2022-03-01 19:02
> 

Sure no rush! It's so bad what's happening in ukraine right now, I hope it will stop soon...

**Comment by pitripit** [comment] 2022-03-03 12:52
@SuchByte, can you please share your test script? i don't understand how to show info of my dual200s.

tnx

**Comment by manuelmayer-dev** [comment] 2022-03-06 17:11
> @SuchByte, can you please share your test script? i don't understand how to show info of my dual200s.
> 
> tnx

Sure, just make sure you installed pyvesync with `pip install pyvesync`, then create a file e.g. `vesync_test.py` and paste the following code into it. Then run it from command line with `python .\vesync_test.py`

```python
from pyvesync import VeSync

manager = VeSync("your@email.com", "Yourpassword", "Your timezon (e.g. Europe/Berlin)")
manager.login()

# Get/Update Devices from server - populate device lists
manager.update()

# Get energy usage data
manager.update_energy()

print("Outlets:")
for device in manager.outlets:
    print(device.display())
    
print("---")
print("Switches:")
for device in manager.switches:
    print(device.display())
    
print("---")
print("Fans:")
for device in manager.fans:
    print(device.display())
    
print("---")
print("Bulbs:")
for device in manager.bulbs:
    print(device.display())
```

**Comment by pitripit** [comment] 2022-03-08 08:06
@SuchByte thank you.

It seems that the problem is the pyvesync version, the 1.4.2 does not display anything, with version 1.4.3 I have an output from your code.

---
Fans:
Device Name:... Umidificatore  
Model: ........ LUH-D301S-WEU  
Subdevice No: . None           
...

i will try if updating pyvesync version on HA changes something in official integration or formatBCE integration.

**Comment by manuelmayer-dev** [comment] 2022-03-12 11:17
> @SuchByte thank you.
> 
> It seems that the problem is the pyvesync version, the 1.4.2 does not display anything, with version 1.4.3 I have an output from your code.
> 
> Fans: Device Name:... Umidificatore Model: ........ LUH-D301S-WEU Subdevice No: . None ...
> 
> i will try if updating pyvesync version on HA changes something in official integration or formatBCE integration.

You were right! I changed the dependency version of pyvesync to 1.4.3 in the manifest and now my modified version works! I created a fork of a fork of this repo which even has some sensors. If you're interessted, you can try it: https://github.com/SuchByte/HA_VeSync_Classic300s

**Comment by pitripit** [comment] 2022-03-14 14:31
Works. Thank you.
Do you think it is possible to merge your code into the official integration?

> > @SuchByte thank you.
> > It seems that the problem is the pyvesync version, the 1.4.2 does not display anything, with version 1.4.3 I have an output from your code.
> > Fans: Device Name:... Umidificatore Model: ........ LUH-D301S-WEU Subdevice No: . None ...
> > i will try if updating pyvesync version on HA changes something in official integration or formatBCE integration.
> 
> You were right! I changed the dependency version of pyvesync to 1.4.3 in the manifest and now my modified version works! I created a fork of a fork of this repo which even has some sensors. If you're interessted, you can try it: https://github.com/SuchByte/HA_VeSync_Classic300s

**Comment by lasry1** [comment] 2022-03-18 09:48
@SuchByte thanks for that with your version i got my humidifier working

**Comment by formatBCE** [comment] 2022-03-18 15:54
Guys, hi. Sorry for being silent these days - I'm Ukrainian, so have a lot of work. :)

Feel free to create pull-requests to update pyvesync and add your awesome changes to this repo, if you want.

Closing this for now.

Cheers.

**Closed as completed** 2022-03-18 15:54 UTC
